import json

ao1 = {
    "ao1":
        {'monthly_avg_daily_temperature': {'GEN': (1.6, '°C'), 'FEB': (3.7, '°C'), 'MAR': (8.0, '°C'),
                                           'APR': (13.0, '°C'), 'MAG': (18.9, '°C'), 'GIU': (22.1, '°C'),
                                           'LUG': (23.3, '°C'), 'AGO': (23.1, '°C'), 'SET': (18.4, '°C'),
                                           'OTT': (14.0, '°C'), 'NOV': (8.1, '°C'), 'DIC': (4.5, '°C')},
         'avg_annual_temperature': (13.3, '°'), 'monthly_avg_horizontal_irradiance_uni10349': {
            'monthly_avg_daily_horizontal_irradiance': {'GEN': (1.22, 'kWh/m2'), 'FEB': (2.3, 'kWh/m2'),
                                                        'MAR': (3.54, 'kWh/m2'), 'APR': (4.28, 'kWh/m2'),
                                                        'MAG': (5.57, 'kWh/m2'), 'GIU': (6.29, 'kWh/m2'),
                                                        'LUG': (6.34, 'kWh/m2'), 'AGO': (5.34, 'kWh/m2'),
                                                        'SET': (3.92, 'kWh/m2'), 'OTT': (2.5, 'kWh/m2'),
                                                        'NOV': (1.39, 'kWh/m2'), 'DIC': (1.26, 'kWh/m2')},
            'monthly_avg_daily_diffuse_horizontal_irradiance': {'GEN': (0.67, 'kWh/m2'), 'FEB': (0.95, 'kWh/m2'),
                                                                'MAR': (1.3, 'kWh/m2'), 'APR': (1.84, 'kWh/m2'),
                                                                'MAG': (2.46, 'kWh/m2'), 'GIU': (2.65, 'kWh/m2'),
                                                                'LUG': (2.46, 'kWh/m2'), 'AGO': (2.39, 'kWh/m2'),
                                                                'SET': (1.84, 'kWh/m2'), 'OTT': (1.19, 'kWh/m2'),
                                                                'NOV': (0.7, 'kWh/m2'), 'DIC': (0.59, 'kWh/m2')},
            'monthly_avg_daily_beam_horizontal_irradiance': {'GEN': (0.55, 'kWh/m2'), 'FEB': (1.35, 'kWh/m2'),
                                                             'MAR': (2.24, 'kWh/m2'), 'APR': (2.44, 'kWh/m2'),
                                                             'MAG': (3.11, 'kWh/m2'), 'GIU': (3.64, 'kWh/m2'),
                                                             'LUG': (3.88, 'kWh/m2'), 'AGO': (2.94, 'kWh/m2'),
                                                             'SET': (2.09, 'kWh/m2'), 'OTT': (1.3, 'kWh/m2'),
                                                             'NOV': (0.69, 'kWh/m2'), 'DIC': (0.67, 'kWh/m2')}},
         'monthly_avg_daily_array_irradiance': {'GEN': (0.52, 'kWh/m2/giorno'), 'FEB': (1.08, 'kWh/m2/giorno'),
                                                'MAR': (1.29, 'kWh/m2/giorno'), 'APR': (1.71, 'kWh/m2/giorno'),
                                                'MAG': (2.28, 'kWh/m2/giorno'), 'GIU': (2.44, 'kWh/m2/giorno'),
                                                'LUG': (2.23, 'kWh/m2/giorno'), 'AGO': (2.21, 'kWh/m2/giorno'),
                                                'SET': (1.74, 'kWh/m2/giorno'), 'OTT': (1.15, 'kWh/m2/giorno'),
                                                'NOV': (0.65, 'kWh/m2/giorno'), 'DIC': (0.63, 'kWh/m2/giorno')},
         'monthly_avg_daily_array_irradiance_classification': {
             'GEN': {'monthly_avg_daily_array_irradiance_classification_value': 0.52,
                     'monthly_avg_daily_array_irradiance_classification_unit': 'kWh/m2/giorno',
                     'monthly_avg_daily_array_irradiance_classification_threshold_value': 3.5,
                     'monthly_avg_daily_array_irradiance_classification_threshold_name': 'Molto Bassa'},
             'FEB': {'monthly_avg_daily_array_irradiance_classification_value': 1.08,
                     'monthly_avg_daily_array_irradiance_classification_unit': 'kWh/m2/giorno',
                     'monthly_avg_daily_array_irradiance_classification_threshold_value': 3.5,
                     'monthly_avg_daily_array_irradiance_classification_threshold_name': 'Molto Bassa'},
             'MAR': {'monthly_avg_daily_array_irradiance_classification_value': 1.29,
                     'monthly_avg_daily_array_irradiance_classification_unit': 'kWh/m2/giorno',
                     'monthly_avg_daily_array_irradiance_classification_threshold_value': 3.5,
                     'monthly_avg_daily_array_irradiance_classification_threshold_name': 'Molto Bassa'},
             'APR': {'monthly_avg_daily_array_irradiance_classification_value': 1.71,
                     'monthly_avg_daily_array_irradiance_classification_unit': 'kWh/m2/giorno',
                     'monthly_avg_daily_array_irradiance_classification_threshold_value': 3.5,
                     'monthly_avg_daily_array_irradiance_classification_threshold_name': 'Molto Bassa'},
             'MAG': {'monthly_avg_daily_array_irradiance_classification_value': 2.28,
                     'monthly_avg_daily_array_irradiance_classification_unit': 'kWh/m2/giorno',
                     'monthly_avg_daily_array_irradiance_classification_threshold_value': 3.5,
                     'monthly_avg_daily_array_irradiance_classification_threshold_name': 'Molto Bassa'},
             'GIU': {'monthly_avg_daily_array_irradiance_classification_value': 2.44,
                     'monthly_avg_daily_array_irradiance_classification_unit': 'kWh/m2/giorno',
                     'monthly_avg_daily_array_irradiance_classification_threshold_value': 3.5,
                     'monthly_avg_daily_array_irradiance_classification_threshold_name': 'Molto Bassa'},
             'LUG': {'monthly_avg_daily_array_irradiance_classification_value': 2.23,
                     'monthly_avg_daily_array_irradiance_classification_unit': 'kWh/m2/giorno',
                     'monthly_avg_daily_array_irradiance_classification_threshold_value': 3.5,
                     'monthly_avg_daily_array_irradiance_classification_threshold_name': 'Molto Bassa'},
             'AGO': {'monthly_avg_daily_array_irradiance_classification_value': 2.21,
                     'monthly_avg_daily_array_irradiance_classification_unit': 'kWh/m2/giorno',
                     'monthly_avg_daily_array_irradiance_classification_threshold_value': 3.5,
                     'monthly_avg_daily_array_irradiance_classification_threshold_name': 'Molto Bassa'},
             'SET': {'monthly_avg_daily_array_irradiance_classification_value': 1.74,
                     'monthly_avg_daily_array_irradiance_classification_unit': 'kWh/m2/giorno',
                     'monthly_avg_daily_array_irradiance_classification_threshold_value': 3.5,
                     'monthly_avg_daily_array_irradiance_classification_threshold_name': 'Molto Bassa'},
             'OTT': {'monthly_avg_daily_array_irradiance_classification_value': 1.15,
                     'monthly_avg_daily_array_irradiance_classification_unit': 'kWh/m2/giorno',
                     'monthly_avg_daily_array_irradiance_classification_threshold_value': 3.5,
                     'monthly_avg_daily_array_irradiance_classification_threshold_name': 'Molto Bassa'},
             'NOV': {'monthly_avg_daily_array_irradiance_classification_value': 0.65,
                     'monthly_avg_daily_array_irradiance_classification_unit': 'kWh/m2/giorno',
                     'monthly_avg_daily_array_irradiance_classification_threshold_value': 3.5,
                     'monthly_avg_daily_array_irradiance_classification_threshold_name': 'Molto Bassa'},
             'DIC': {'monthly_avg_daily_array_irradiance_classification_value': 0.63,
                     'monthly_avg_daily_array_irradiance_classification_unit': 'kWh/m2/giorno',
                     'monthly_avg_daily_array_irradiance_classification_threshold_value': 3.5,
                     'monthly_avg_daily_array_irradiance_classification_threshold_name': 'Molto Bassa'}},
         'monthly_plane_of_array_irradiance': {'GEN': (16.12, 'MWh/mq'), 'FEB': (30.51, 'MWh/mq'),
                                               'MAR': (39.99, 'MWh/mq'), 'APR': (51.3, 'MWh/mq'),
                                               'MAG': (70.68, 'MWh/mq'), 'GIU': (73.2, 'MWh/mq'),
                                               'LUG': (69.13, 'MWh/mq'), 'AGO': (68.51, 'MWh/mq'),
                                               'SET': (52.2, 'MWh/mq'), 'OTT': (35.65, 'MWh/mq'),
                                               'NOV': (19.5, 'MWh/mq'), 'DIC': (19.53, 'MWh/mq')},
         'annual_solar_radiation': (546.32, 'kWh/m2/anno'), 'theoretical_annual_yield': (546.32, 'kWh/kWp'),
         'monthly_avg_daylight_hours': {'GEN': (8.93, 'h'), 'FEB': (10.18, 'h'), 'MAR': (11.67, 'h'),
                                        'APR': (13.3, 'h'), 'MAG': (14.72, 'h'), 'GIU': (15.45, 'h'),
                                        'LUG': (15.12, 'h'), 'AGO': (13.89, 'h'), 'SET': (12.3, 'h'),
                                        'OTT': (10.67, 'h'), 'NOV': (9.26, 'h'), 'DIC': (8.56, 'h')},
         'annual_avg_daylight_hours': (12.02, 'h'), 'monthly_avg_daily_horizontal_solar_irradiance_summary': {
            'monthly_avg_daily_horizontal_irradiance': {'GEN': (0.67, 'kWh/m2'), 'FEB': (0.95, 'kWh/m2'),
                                                        'MAR': (1.3, 'kWh/m2'), 'APR': (1.84, 'kWh/m2'),
                                                        'MAG': (2.46, 'kWh/m2'), 'GIU': (2.65, 'kWh/m2'),
                                                        'LUG': (2.46, 'kWh/m2'), 'AGO': (2.39, 'kWh/m2'),
                                                        'SET': (1.84, 'kWh/m2'), 'OTT': (1.19, 'kWh/m2'),
                                                        'NOV': (0.7, 'kWh/m2'), 'DIC': (0.59, 'kWh/m2')},
            'monthly_avg_daily_diffuse_horizontal_irradiance': {'GEN': (1.22, 'kWh/m2'), 'FEB': (2.3, 'kWh/m2'),
                                                                'MAR': (3.54, 'kWh/m2'), 'APR': (4.28, 'kWh/m2'),
                                                                'MAG': (5.57, 'kWh/m2'), 'GIU': (6.29, 'kWh/m2'),
                                                                'LUG': (6.34, 'kWh/m2'), 'AGO': (5.34, 'kWh/m2'),
                                                                'SET': (3.92, 'kWh/m2'), 'OTT': (2.5, 'kWh/m2'),
                                                                'NOV': (1.39, 'kWh/m2'), 'DIC': (1.26, 'kWh/m2')},
            'monthly_avg_daily_beam_horizontal_irradiance': {'GEN': (0.55, 'kWh/m2'), 'FEB': (1.35, 'kWh/m2'),
                                                             'MAR': (2.24, 'kWh/m2'), 'APR': (2.44, 'kWh/m2'),
                                                             'MAG': (3.11, 'kWh/m2'), 'GIU': (3.64, 'kWh/m2'),
                                                             'LUG': (3.88, 'kWh/m2'), 'AGO': (2.94, 'kWh/m2'),
                                                             'SET': (2.09, 'kWh/m2'), 'OTT': (1.3, 'kWh/m2'),
                                                             'NOV': (0.69, 'kWh/m2'), 'DIC': (0.67, 'kWh/m2')},
            'monthly_avg_daily_reflected_horizontal_irradiance': {'GEN': (0.13, 'kWh/m2/giorno'),
                                                                  'FEB': (0.19, 'kWh/m2/giorno'),
                                                                  'MAR': (0.26, 'kWh/m2/giorno'),
                                                                  'APR': (0.37, 'kWh/m2/giorno'),
                                                                  'MAG': (0.49, 'kWh/m2/giorno'),
                                                                  'GIU': (0.53, 'kWh/m2/giorno'),
                                                                  'LUG': (0.49, 'kWh/m2/giorno'),
                                                                  'AGO': (0.48, 'kWh/m2/giorno'),
                                                                  'SET': (0.37, 'kWh/m2/giorno'),
                                                                  'OTT': (0.24, 'kWh/m2/giorno'),
                                                                  'NOV': (0.14, 'kWh/m2/giorno'),
                                                                  'DIC': (0.12, 'kWh/m2/giorno')}},
         'fixed_sys_monthly_temp_loss': {'GEN': (-1.7, '%'), 'FEB': (-0.65, '%'), 'MAR': (1.5, '%'), 'APR': (4.0, '%'),
                                         'MAG': (6.95, '%'), 'GIU': (8.55, '%'), 'LUG': (9.15, '%'), 'AGO': (9.05, '%'),
                                         'SET': (6.7, '%'), 'OTT': (4.5, '%'), 'NOV': (1.55, '%'), 'DIC': (-0.25, '%')},
         'fixed_sys_empirical_temp_loss': {'GEN': (5.39, '%/°C'), 'FEB': (5.39, '%/°C'), 'MAR': (5.39, '%/°C'),
                                           'APR': (5.39, '%/°C'), 'MAG': (5.39, '%/°C'), 'GIU': (5.39, '%/°C'),
                                           'LUG': (5.39, '%/°C'), 'AGO': (5.39, '%/°C'), 'SET': (5.39, '%/°C'),
                                           'OTT': (5.39, '%/°C'), 'NOV': (5.39, '%/°C'), 'DIC': (5.39, '%/°C')},
         'fixed_sys_monthly_reflection_loss': {'GEN': (3.0, '%'), 'FEB': (3.0, '%'), 'MAR': (3.0, '%'),
                                               'APR': (3.0, '%'), 'MAG': (3.0, '%'), 'GIU': (3.0, '%'),
                                               'LUG': (3.0, '%'), 'AGO': (3.0, '%'), 'SET': (3.0, '%'),
                                               'OTT': (3.0, '%'), 'NOV': (3.0, '%'), 'DIC': (3.0, '%')},
         'fixed_sys_monthly_soiling_loss': {'GEN': (1.0, '%'), 'FEB': (1.0, '%'), 'MAR': (1.0, '%'), 'APR': (1.0, '%'),
                                            'MAG': (1.0, '%'), 'GIU': (1.0, '%'), 'LUG': (1.0, '%'), 'AGO': (1.0, '%'),
                                            'SET': (1.0, '%'), 'OTT': (1.0, '%'), 'NOV': (1.0, '%'), 'DIC': (1.0, '%')},
         'fixed_sys_monthly_low_irradiance_loss': {'GEN': (0.07, '%'), 'FEB': (0.07, '%'), 'MAR': (0.07, '%'),
                                                   'APR': (0.07, '%'), 'MAG': (0.07, '%'), 'GIU': (0.07, '%'),
                                                   'LUG': (0.07, '%'), 'AGO': (0.07, '%'), 'SET': (0.07, '%'),
                                                   'OTT': (0.07, '%'), 'NOV': (0.07, '%'), 'DIC': (0.07, '%')},
         'fixed_sys_monthly_mismatching_loss': {'GEN': (2.0, '%'), 'FEB': (2.0, '%'), 'MAR': (2.0, '%'),
                                                'APR': (2.0, '%'), 'MAG': (2.0, '%'), 'GIU': (2.0, '%'),
                                                'LUG': (2.0, '%'), 'AGO': (2.0, '%'), 'SET': (2.0, '%'),
                                                'OTT': (2.0, '%'), 'NOV': (2.0, '%'), 'DIC': (2.0, '%')},
         'fixed_sys_monthly_cable_loss': {'GEN': (0.67, '%'), 'FEB': (0.67, '%'), 'MAR': (0.67, '%'),
                                          'APR': (0.67, '%'), 'MAG': (0.67, '%'), 'GIU': (0.67, '%'),
                                          'LUG': (0.67, '%'), 'AGO': (0.67, '%'), 'SET': (0.67, '%'),
                                          'OTT': (0.67, '%'), 'NOV': (0.67, '%'), 'DIC': (0.67, '%')},
         'fixed_sys_monthly_inverter_loss': {'GEN': (3.0, '%'), 'FEB': (3.0, '%'), 'MAR': (3.0, '%'), 'APR': (3.0, '%'),
                                             'MAG': (3.0, '%'), 'GIU': (3.0, '%'), 'LUG': (3.0, '%'), 'AGO': (3.0, '%'),
                                             'SET': (3.0, '%'), 'OTT': (3.0, '%'), 'NOV': (3.0, '%'),
                                             'DIC': (3.0, '%')},
         'fixed_sys_monthly_other_loss': {'GEN': (1.0, '%'), 'FEB': (1.0, '%'), 'MAR': (1.0, '%'), 'APR': (1.0, '%'),
                                          'MAG': (1.0, '%'), 'GIU': (1.0, '%'), 'LUG': (1.0, '%'), 'AGO': (1.0, '%'),
                                          'SET': (1.0, '%'), 'OTT': (1.0, '%'), 'NOV': (1.0, '%'), 'DIC': (1.0, '%')},
         'fixed_sys_monthly_obstacle_shading': {'GEN': (2.2, '%'), 'FEB': (2.2, '%'), 'MAR': (2.2, '%'),
                                                'APR': (2.2, '%'), 'MAG': (2.2, '%'), 'GIU': (2.2, '%'),
                                                'LUG': (2.2, '%'), 'AGO': (2.2, '%'), 'SET': (2.2, '%'),
                                                'OTT': (2.2, '%'), 'NOV': (2.2, '%'), 'DIC': (2.2, '%')},
         'fixed_sys_monthly_clinometric_shading': {'GEN': (3.1, '%'), 'FEB': (3.1, '%'), 'MAR': (3.1, '%'),
                                                   'APR': (3.1, '%'), 'MAG': (3.1, '%'), 'GIU': (3.1, '%'),
                                                   'LUG': (3.1, '%'), 'AGO': (3.1, '%'), 'SET': (3.1, '%'),
                                                   'OTT': (3.1, '%'), 'NOV': (3.1, '%'), 'DIC': (3.1, '%')},
         'fixed_sys_monthly_shading_loss_percentage': {'GEN': (2.76, '%'), 'FEB': (2.76, '%'), 'MAR': (2.76, '%'),
                                                       'APR': (2.76, '%'), 'MAG': (2.76, '%'), 'GIU': (2.76, '%'),
                                                       'LUG': (2.76, '%'), 'AGO': (2.76, '%'), 'SET': (2.76, '%'),
                                                       'OTT': (2.76, '%'), 'NOV': (2.76, '%'), 'DIC': (2.76, '%')},
         'fixed_sys_monthly_shading_loss': {'GEN': (0.44, 'kWh/mq'), 'FEB': (0.84, 'kWh/mq'), 'MAR': (1.1, 'kWh/mq'),
                                            'APR': (1.42, 'kWh/mq'), 'MAG': (1.95, 'kWh/mq'), 'GIU': (2.02, 'kWh/mq'),
                                            'LUG': (1.91, 'kWh/mq'), 'AGO': (1.89, 'kWh/mq'), 'SET': (1.44, 'kWh/mq'),
                                            'OTT': (0.98, 'kWh/mq'), 'NOV': (0.54, 'kWh/mq'), 'DIC': (0.54, 'kWh/mq')},
         'fixed_sys_annual_shading_loss': (15.07, 'kWh/mq'), 'monthly_system_losses_summary': {
            'fixed_sys_monthly_temp_loss': {'GEN': (-1.7, '%'), 'FEB': (-0.65, '%'), 'MAR': (1.5, '%'),
                                            'APR': (4.0, '%'), 'MAG': (6.95, '%'), 'GIU': (8.55, '%'),
                                            'LUG': (9.15, '%'), 'AGO': (9.05, '%'), 'SET': (6.7, '%'),
                                            'OTT': (4.5, '%'), 'NOV': (1.55, '%'), 'DIC': (-0.25, '%')},
            'fixed_sys_monthly_reflection_loss': {'GEN': (3.0, '%'), 'FEB': (3.0, '%'), 'MAR': (3.0, '%'),
                                                  'APR': (3.0, '%'), 'MAG': (3.0, '%'), 'GIU': (3.0, '%'),
                                                  'LUG': (3.0, '%'), 'AGO': (3.0, '%'), 'SET': (3.0, '%'),
                                                  'OTT': (3.0, '%'), 'NOV': (3.0, '%'), 'DIC': (3.0, '%')},
            'fixed_sys_monthly_soiling_loss': {'GEN': (1.0, '%'), 'FEB': (1.0, '%'), 'MAR': (1.0, '%'),
                                               'APR': (1.0, '%'), 'MAG': (1.0, '%'), 'GIU': (1.0, '%'),
                                               'LUG': (1.0, '%'), 'AGO': (1.0, '%'), 'SET': (1.0, '%'),
                                               'OTT': (1.0, '%'), 'NOV': (1.0, '%'), 'DIC': (1.0, '%')},
            'fixed_sys_monthly_low_irradiance_loss': {'GEN': (0.07, '%'), 'FEB': (0.07, '%'), 'MAR': (0.07, '%'),
                                                      'APR': (0.07, '%'), 'MAG': (0.07, '%'), 'GIU': (0.07, '%'),
                                                      'LUG': (0.07, '%'), 'AGO': (0.07, '%'), 'SET': (0.07, '%'),
                                                      'OTT': (0.07, '%'), 'NOV': (0.07, '%'), 'DIC': (0.07, '%')},
            'fixed_sys_monthly_mismatching_loss': {'GEN': (2.0, '%'), 'FEB': (2.0, '%'), 'MAR': (2.0, '%'),
                                                   'APR': (2.0, '%'), 'MAG': (2.0, '%'), 'GIU': (2.0, '%'),
                                                   'LUG': (2.0, '%'), 'AGO': (2.0, '%'), 'SET': (2.0, '%'),
                                                   'OTT': (2.0, '%'), 'NOV': (2.0, '%'), 'DIC': (2.0, '%')},
            'fixed_sys_monthly_cable_loss': {'GEN': (0.67, '%'), 'FEB': (0.67, '%'), 'MAR': (0.67, '%'),
                                             'APR': (0.67, '%'), 'MAG': (0.67, '%'), 'GIU': (0.67, '%'),
                                             'LUG': (0.67, '%'), 'AGO': (0.67, '%'), 'SET': (0.67, '%'),
                                             'OTT': (0.67, '%'), 'NOV': (0.67, '%'), 'DIC': (0.67, '%')},
            'fixed_sys_monthly_inverter_loss': {'GEN': (3.0, '%'), 'FEB': (3.0, '%'), 'MAR': (3.0, '%'),
                                                'APR': (3.0, '%'), 'MAG': (3.0, '%'), 'GIU': (3.0, '%'),
                                                'LUG': (3.0, '%'), 'AGO': (3.0, '%'), 'SET': (3.0, '%'),
                                                'OTT': (3.0, '%'), 'NOV': (3.0, '%'), 'DIC': (3.0, '%')},
            'fixed_sys_monthly_other_loss': {'GEN': (1.0, '%'), 'FEB': (1.0, '%'), 'MAR': (1.0, '%'), 'APR': (1.0, '%'),
                                             'MAG': (1.0, '%'), 'GIU': (1.0, '%'), 'LUG': (1.0, '%'), 'AGO': (1.0, '%'),
                                             'SET': (1.0, '%'), 'OTT': (1.0, '%'), 'NOV': (1.0, '%'),
                                             'DIC': (1.0, '%')}}, 'monthly_system_efficiency_summary': {
            'monthly_system_efficiency_summary': {
                'fixed_sys_monthly_temp_efficiency': {'GEN': (0.0, '%'), 'FEB': (0.0, '%'), 'MAR': (0.0, '%'),
                                                      'APR': (0.0, '%'), 'MAG': (0.0, '%'), 'GIU': (0.0, '%'),
                                                      'LUG': (0.0, '%'), 'AGO': (0.0, '%'), 'SET': (0.0, '%'),
                                                      'OTT': (0.0, '%'), 'NOV': (0.0, '%'), 'DIC': (0.0, '%')},
                'fixed_sys_monthly_reflection_efficiency': {'GEN': (0.0, '%'), 'FEB': (0.0, '%'), 'MAR': (0.0, '%'),
                                                            'APR': (0.0, '%'), 'MAG': (0.0, '%'), 'GIU': (0.0, '%'),
                                                            'LUG': (0.0, '%'), 'AGO': (0.0, '%'), 'SET': (0.0, '%'),
                                                            'OTT': (0.0, '%'), 'NOV': (0.0, '%'), 'DIC': (0.0, '%')},
                'fixed_sys_monthly_soiling_efficiency': {'GEN': (0.0, '%'), 'FEB': (0.0, '%'), 'MAR': (0.0, '%'),
                                                         'APR': (0.0, '%'), 'MAG': (0.0, '%'), 'GIU': (0.0, '%'),
                                                         'LUG': (0.0, '%'), 'AGO': (0.0, '%'), 'SET': (0.0, '%'),
                                                         'OTT': (0.0, '%'), 'NOV': (0.0, '%'), 'DIC': (0.0, '%')},
                'fixed_sys_monthly_low_irradiance_efficiency': {'GEN': (0.0, '%'), 'FEB': (0.0, '%'), 'MAR': (0.0, '%'),
                                                                'APR': (0.0, '%'), 'MAG': (0.0, '%'), 'GIU': (0.0, '%'),
                                                                'LUG': (0.0, '%'), 'AGO': (0.0, '%'), 'SET': (0.0, '%'),
                                                                'OTT': (0.0, '%'), 'NOV': (0.0, '%'),
                                                                'DIC': (0.0, '%')},
                'fixed_sys_monthly_mismatching_efficiency': {'GEN': (0.0, '%'), 'FEB': (0.0, '%'), 'MAR': (0.0, '%'),
                                                             'APR': (0.0, '%'), 'MAG': (0.0, '%'), 'GIU': (0.0, '%'),
                                                             'LUG': (0.0, '%'), 'AGO': (0.0, '%'), 'SET': (0.0, '%'),
                                                             'OTT': (0.0, '%'), 'NOV': (0.0, '%'), 'DIC': (0.0, '%')},
                'fixed_sys_monthly_cable_efficiency': {'GEN': (0.0, '%'), 'FEB': (0.0, '%'), 'MAR': (0.0, '%'),
                                                       'APR': (0.0, '%'), 'MAG': (0.0, '%'), 'GIU': (0.0, '%'),
                                                       'LUG': (0.0, '%'), 'AGO': (0.0, '%'), 'SET': (0.0, '%'),
                                                       'OTT': (0.0, '%'), 'NOV': (0.0, '%'), 'DIC': (0.0, '%')},
                'fixed_sys_monthly_inverter_efficiency': {'GEN': (0.0, '%'), 'FEB': (0.0, '%'), 'MAR': (0.0, '%'),
                                                          'APR': (0.0, '%'), 'MAG': (0.0, '%'), 'GIU': (0.0, '%'),
                                                          'LUG': (0.0, '%'), 'AGO': (0.0, '%'), 'SET': (0.0, '%'),
                                                          'OTT': (0.0, '%'), 'NOV': (0.0, '%'), 'DIC': (0.0, '%')},
                'fixed_sys_monthly_other_efficiency': {'GEN': (0.0, '%'), 'FEB': (0.0, '%'), 'MAR': (0.0, '%'),
                                                       'APR': (0.0, '%'), 'MAG': (0.0, '%'), 'GIU': (0.0, '%'),
                                                       'LUG': (0.0, '%'), 'AGO': (0.0, '%'), 'SET': (0.0, '%'),
                                                       'OTT': (0.0, '%'), 'NOV': (0.0, '%'), 'DIC': (0.0, '%')}},
            'fixed_sys_monthly_temp_efficiency': {'GEN': (101.7, '%'), 'FEB': (100.65, '%'), 'MAR': (98.5, '%'),
                                                  'APR': (96.0, '%'), 'MAG': (93.05, '%'), 'GIU': (91.45, '%'),
                                                  'LUG': (90.85, '%'), 'AGO': (90.95, '%'), 'SET': (93.3, '%'),
                                                  'OTT': (95.5, '%'), 'NOV': (98.45, '%'), 'DIC': (100.25, '%')},
            'fixed_sys_monthly_reflection_efficiency': {'GEN': (97.0, '%'), 'FEB': (97.0, '%'), 'MAR': (97.0, '%'),
                                                        'APR': (97.0, '%'), 'MAG': (97.0, '%'), 'GIU': (97.0, '%'),
                                                        'LUG': (97.0, '%'), 'AGO': (97.0, '%'), 'SET': (97.0, '%'),
                                                        'OTT': (97.0, '%'), 'NOV': (97.0, '%'), 'DIC': (97.0, '%')},
            'fixed_sys_monthly_soiling_efficiency': {'GEN': (99.0, '%'), 'FEB': (99.0, '%'), 'MAR': (99.0, '%'),
                                                     'APR': (99.0, '%'), 'MAG': (99.0, '%'), 'GIU': (99.0, '%'),
                                                     'LUG': (99.0, '%'), 'AGO': (99.0, '%'), 'SET': (99.0, '%'),
                                                     'OTT': (99.0, '%'), 'NOV': (99.0, '%'), 'DIC': (99.0, '%')},
            'fixed_sys_monthly_low_irradiance_efficiency': {'GEN': (99.93, '%'), 'FEB': (99.93, '%'),
                                                            'MAR': (99.93, '%'), 'APR': (99.93, '%'),
                                                            'MAG': (99.93, '%'), 'GIU': (99.93, '%'),
                                                            'LUG': (99.93, '%'), 'AGO': (99.93, '%'),
                                                            'SET': (99.93, '%'), 'OTT': (99.93, '%'),
                                                            'NOV': (99.93, '%'), 'DIC': (99.93, '%')},
            'fixed_sys_monthly_mismatching_efficiency': {'GEN': (98.0, '%'), 'FEB': (98.0, '%'), 'MAR': (98.0, '%'),
                                                         'APR': (98.0, '%'), 'MAG': (98.0, '%'), 'GIU': (98.0, '%'),
                                                         'LUG': (98.0, '%'), 'AGO': (98.0, '%'), 'SET': (98.0, '%'),
                                                         'OTT': (98.0, '%'), 'NOV': (98.0, '%'), 'DIC': (98.0, '%')},
            'fixed_sys_monthly_cable_efficiency': {'GEN': (99.33, '%'), 'FEB': (99.33, '%'), 'MAR': (99.33, '%'),
                                                   'APR': (99.33, '%'), 'MAG': (99.33, '%'), 'GIU': (99.33, '%'),
                                                   'LUG': (99.33, '%'), 'AGO': (99.33, '%'), 'SET': (99.33, '%'),
                                                   'OTT': (99.33, '%'), 'NOV': (99.33, '%'), 'DIC': (99.33, '%')},
            'fixed_sys_monthly_inverter_efficiency': {'GEN': (97.0, '%'), 'FEB': (97.0, '%'), 'MAR': (97.0, '%'),
                                                      'APR': (97.0, '%'), 'MAG': (97.0, '%'), 'GIU': (97.0, '%'),
                                                      'LUG': (97.0, '%'), 'AGO': (97.0, '%'), 'SET': (97.0, '%'),
                                                      'OTT': (97.0, '%'), 'NOV': (97.0, '%'), 'DIC': (97.0, '%')},
            'fixed_sys_monthly_other_efficiency': {'GEN': (99.0, '%'), 'FEB': (99.0, '%'), 'MAR': (99.0, '%'),
                                                   'APR': (99.0, '%'), 'MAG': (99.0, '%'), 'GIU': (99.0, '%'),
                                                   'LUG': (99.0, '%'), 'AGO': (99.0, '%'), 'SET': (99.0, '%'),
                                                   'OTT': (99.0, '%'), 'NOV': (99.0, '%'), 'DIC': (99.0, '%')}},
         'monthly_net_energy': {'GEN': (0.08, 'kWh/m2/mese'), 'FEB': (0.24, 'kWh/m2/mese'),
                                'MAR': (0.19, 'kWh/m2/mese'), 'APR': (0.29, 'kWh/m2/mese'),
                                'MAG': (0.33, 'kWh/m2/mese'), 'GIU': (0.42, 'kWh/m2/mese'),
                                'LUG': (0.32, 'kWh/m2/mese'), 'AGO': (0.32, 'kWh/m2/mese'), 'SET': (0.3, 'kWh/m2/mese'),
                                'OTT': (0.17, 'kWh/m2/mese'), 'NOV': (0.11, 'kWh/m2/mese'),
                                'DIC': (0.09, 'kWh/m2/mese')}, 'annual_net_energy': (531.25, 'kWh/m2/anno'),
         'monthly_efficiency_percentage': {'GEN': (91.23, '%'), 'FEB': (90.29, '%'), 'MAR': (88.36, '%'),
                                           'APR': (86.12, '%'), 'MAG': (83.47, '%'), 'GIU': (82.04, '%'),
                                           'LUG': (81.5, '%'), 'AGO': (81.59, '%'), 'SET': (83.69, '%'),
                                           'OTT': (85.67, '%'), 'NOV': (88.31, '%'), 'DIC': (89.93, '%')},
         'monthly_energy_yield': {'GEN': (0.07, 'kWh/kWp'), 'FEB': (0.22, 'kWh/kWp'), 'MAR': (0.17, 'kWh/kWp'),
                                  'APR': (0.25, 'kWh/kWp'), 'MAG': (0.28, 'kWh/kWp'), 'GIU': (0.34, 'kWh/kWp'),
                                  'LUG': (0.26, 'kWh/kWp'), 'AGO': (0.26, 'kWh/kWp'), 'SET': (0.25, 'kWh/kWp'),
                                  'OTT': (0.15, 'kWh/kWp'), 'NOV': (0.1, 'kWh/kWp'), 'DIC': (0.08, 'kWh/kWp')},
         'annual_energy_yield': (2.43, 'kWh/kWp'), 'system_efficiency': (0.46, '%'),
         'daily_avg_energy_yield': {'GEN': (0.0, 'kWh/m2'), 'FEB': (0.01, 'kWh/m2'), 'MAR': (0.01, 'kWh/m2'),
                                    'APR': (0.01, 'kWh/m2'), 'MAG': (0.01, 'kWh/m2'), 'GIU': (0.01, 'kWh/m2'),
                                    'LUG': (0.01, 'kWh/m2'), 'AGO': (0.01, 'kWh/m2'), 'SET': (0.01, 'kWh/m2'),
                                    'OTT': (0.0, 'kWh/m2'), 'NOV': (0.0, 'kWh/m2'), 'DIC': (0.0, 'kWh/m2')},
         'daily_energy_yield': (0.01, 'kWh/kWp'),
         'monthly_avg_energy_production': {'GEN': (105.0, 'kWh'), 'FEB': (330.0, 'kWh'), 'MAR': (255.0, 'kWh'),
                                           'APR': (375.0, 'kWh'), 'MAG': (420.0, 'kWh'), 'GIU': (510.0, 'kWh'),
                                           'LUG': (390.0, 'kWh'), 'AGO': (390.0, 'kWh'), 'SET': (375.0, 'kWh'),
                                           'OTT': (225.0, 'kWh'), 'NOV': (150.0, 'kWh'), 'DIC': (120.0, 'kWh')},
         'annual_energy_production': (3645.0, 'kWh'), 'annual_loss_percentage': (99.56, '%'),
         'annual_loss_percentage_classification': {'annual_loss_percentage_value': 99.56,
                                                   'annual_loss_percentage_class': 'Molto Alta',
                                                   'annual_loss_percentage_comment': 'Le perdite molto alte indicano una situazione critica in cui l’impianto ha prestazioni gravemente compromesse. In questa classe, oltre il 25% dell’energia teorica viene dispersa o non convertita sufficientemente.'},
         'annual_net_energy_classification': {'annual_net_energy_value': 531.25,
                                              'annual_net_energy_class': 'Molto bassa',
                                              'annual_net_energy_comment': 'L’area presenta una bassissima irradiazione, poco favorevole per impianti fotovoltaici.'},
         'system_efficiency_classification': {'system_efficiency_value': 0.46,
                                              'system_efficiency_energy_class': 'Molto bassa',
                                              'system_efficiency_energy_comment': "Generalmente gli impianti tipici di questa classe presentano una notevole quantità di perdite. Questa bassa efficienza può essere dovuta a una serie di problemi come un alto grado di ombreggiamento, un'inclinazione subottimale dei pannelli, moduli fotovoltaici di qualità scadente, o inverter inefficaci. Anche temperature elevate senza adeguata ventilazione possono ridurre sensibilmente le prestazioni."},
         'green_house_gases_reduction': {'co2_reduction': (838.35, 'kg CO2/anno'),
                                         'ch4_reduction': (54.67, 'kg CH4/anno'),
                                         'n2o_reduction': (0.73, 'kg N2O/anno'),
                                         'ch4_co2_eq_reduction': (1530.9, 'kg CO2/anno'),
                                         'n2o_co2_eq_reduction': (199.02, 'kg CO2/anno'),
                                         'ghg_co2_eq_reduction_annual': (2568.27, 'kg CO2/anno'),
                                         'ghg_co2_eq_reduction_total': (51365.34, 'kg CO2/anno'),
                                         'ghg_co2_eq_reduction_total_tons': (51.37, 't CO2/anno')},
         't_e_p_reduction': {'tep_reduction': (6.27, 'TEP'),
                             'tep_reduction_comment': '6.27 TEP evitati in 20 anni di esercizio'}}
}

print(ao1)

# Esportazione in formato JSON
with open("ao1.json", "w", encoding="utf-8") as json_file:
    json.dump(ao1, json_file, ensure_ascii=False, indent=4)

print("Dizionario esportato in output.json")

