# Generated by Django 5.0.6 on 2024-09-18 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectsession',
            name='session_data',
            field=models.TextField(default=''),
        ),
    ]
