# Generated by Django 5.0.6 on 2024-10-01 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_projectsession_session_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectsession',
            name='pvgis_data',
            field=models.TextField(default=''),
        ),
    ]
