# Generated by Django 5.0.6 on 2024-10-09 08:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectsession',
            name='pvgis_data',
        ),
        migrations.AddField(
            model_name='projectsession',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='projectsession',
            name='session_end',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='projectsession',
            name='session_start',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='projectsession',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
