# Generated by Django 5.0.6 on 2024-10-09 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_remove_projectsession_pvgis_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.SmallIntegerField(default=1),
        ),
    ]
