# Generated by Django 5.0.6 on 2024-10-24 06:41

import apps.project.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_designer'),
    ]

    operations = [
        migrations.AddField(
            model_name='designer',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=apps.project.models.user_directory_path),
        ),
    ]
