# Generated by Django 5.0.6 on 2024-10-24 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_designer_logo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='designer',
            old_name='user_id',
            new_name='user',
        ),
    ]
