# Generated by Django 5.0.6 on 2024-10-24 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_rename_user_id_designer_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designer',
            name='designer_data',
            field=models.JSONField(),
        ),
    ]
