# Generated by Django 5.0.6 on 2024-10-24 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_alter_designer_designer_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designer',
            name='designer_data',
            field=models.TextField(default=''),
        ),
    ]
