# Generated by Django 5.0.6 on 2024-10-24 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0011_alter_designer_designer_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designer',
            name='designer_data',
            field=models.JSONField(default=dict),
        ),
    ]
