# Generated by Django 5.0.6 on 2024-11-08 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0012_alter_designer_designer_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='pdf_file',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='project',
            name='word_file',
            field=models.TextField(default=''),
        ),
    ]
