# Generated by Django 5.0.6 on 2024-11-08 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0013_project_pdf_file_project_word_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='T3',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.IntegerField(blank=True, null=True)),
                ('template', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 't3',
            },
        ),
        migrations.CreateModel(
            name='T4',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('template', models.TextField(blank=True, null=True)),
                ('id_template', models.ForeignKey(blank=True, db_column='id_template', null=True, on_delete=django.db.models.deletion.CASCADE, to='project.t3')),
            ],
            options={
                'db_table': 't4',
            },
        ),
        migrations.CreateModel(
            name='T5',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.IntegerField(blank=True, null=True)),
                ('output_data', models.JSONField(blank=True, null=True)),
                ('template', models.TextField(blank=True, null=True)),
                ('word_path', models.CharField(blank=True, max_length=255, null=True)),
                ('pdf_path', models.CharField(blank=True, max_length=255, null=True)),
                ('id_template', models.ForeignKey(blank=True, db_column='id_template', null=True, on_delete=django.db.models.deletion.CASCADE, to='project.t3')),
            ],
            options={
                'db_table': 't5',
            },
        ),
    ]
