# Generated by Django 5.0.6 on 2024-11-13 08:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0014_t3_t4_t5'),
    ]

    operations = [
        migrations.AddField(
            model_name='counter',
            name='time_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='projectsession',
            name='session_end',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
