# Generated by Django 5.0.6 on 2024-11-15 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0015_counter_time_at_alter_projectsession_session_end'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='keopebank',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
