# Generated by Django 5.0.6 on 2024-11-20 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0017_alter_project_keopebank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='keopebank',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
