# Generated by Django 5.0.6 on 2025-02-17 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0018_alter_project_keopebank'),
    ]

    operations = [
        migrations.RenameField(
            model_name='t3',
            old_name='code',
            new_name='project_id',
        ),
        migrations.RenameField(
            model_name='t3',
            old_name='template',
            new_name='xml',
        ),
    ]
