# Generated by Django 5.0.6 on 2025-07-24 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0019_rename_code_t3_project_id_rename_template_t3_xml'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='t4',
            name='id_template',
        ),
        migrations.RemoveField(
            model_name='t5',
            name='id_template',
        ),
        migrations.DeleteModel(
            name='ProjectSession',
        ),
        migrations.DeleteModel(
            name='T4',
        ),
        migrations.DeleteModel(
            name='T3',
        ),
        migrations.DeleteModel(
            name='T5',
        ),
    ]
